services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "9912:3306"
    profiles:
      - "dev"
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: sarangbang
    volumes:
      - sarangbang-data:/var/lib/mysql
    networks:
      - sarangbang-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - sarangbang-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8090:8081"  # 웹 UI 접근 포트
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - sarangbang-network
    restart: always

volumes:
  mongo-data:
  sarangbang-data:

networks:
  sarangbang-network:
    driver: bridge
