spring:
  application:
    name: sarangbang
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  access-secret: ${ACCESS_TOKEN_SECRET:LhVYSkvR90p9A7jPFlWWZ0uB3RPiIGnN8s3aXk2lbE4=}

app:
  upload:
    max-file-size: 5242880  # 5MB
    allowed-image-types: image/jpeg,image/jpg,image/png,image/gif,image/webp

  storage:
    type: ${STORAGE_TYPE:minio}
    endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
    bucket-name: ${STORAGE_BUCKET:sarangbang-files}
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health