spring:
  application:
    name: sarangbang
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:client-id-placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:client-secret-placeholder}
            scope: openid, email, profile
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/login/oauth2/code/google}
            authorization-grant-type: authorization_code

          naver:
            client-id: ${NAVER_CLIENT_ID:client-id-placeholder}
            client-secret: ${NAVER_CLIENT_SECRET:client-secret-placeholder}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI:http://localhost:8080/api/login/oauth2/code/naver}
            scope: name, email
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID:client-id-placeholder}
            client-secret: ${KAKAO_CLIENT_SECRET:client-secret-placeholder}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/login/oauth2/code/kakao}
            scope: account_email
            client-name: Kakao

        provider:
          google:
            issuer-uri: https://accounts.google.com

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
oauth2:
  success:
    redirect:
      uri: ${OAUTH2_SUCCESS_REDIRECT_URI:http://localhost:3000/auth/success}

jwt:
  access-secret: ${ACCESS_TOKEN_SECRET:LhVYSkvR90p9A7jPFlWWZ0uB3RPiIGnN8s3aXk2lbE4=}
  refresh-secret: ${REFRESH_TOKEN_SECRET:R4pW6qB1yH3aF7gK0jM5nC_U8iE2bT6dY9lX-cZ1vA4wS7hG3fJ0ko9zL2VeN8s}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  upload:
    max-file-size: 5242880  # 5MB
    allowed-image-types: image/jpeg,image/jpg,image/png,image/gif,image/webp

  storage:
    type: ${STORAGE_TYPE:minio}
    endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
    bucket-name: ${STORAGE_BUCKET:ilsim-uploaded-files}
    access-key: ${STORAGE_ACCESS_KEY:minioadmin}
    secret-key: ${STORAGE_SECRET_KEY:minioadmin123}

management:
  endpoints:
    web:
      exposure:
        include: health