spring:
  application:
    name: sarangbang
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  access-secret: ${ACCESS_TOKEN_SECRET:LhVYSkvR90p9A7jPFlWWZ0uB3RPiIGnN8s3aXk2lbE4=}
