name: Spring Boot CI/CD (Prod)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test -Pprofile=prod

      - name: Configure AWS Credentials for OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHubActionsDeploymentRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 (Prod)
        run: |
          echo "${{ secrets.PROD_EC2_SSH_PRIVATE_KEY_BACK }}" > private_key.pem
          chmod 400 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem -J ec2-user@${{ secrets.BASTION_HOST_PUBLIC_IP }} ec2-user@${{ secrets.PROD_EC2_PRIVATE_IP }} "cd /home/ec2-user/backend && bash deploy.sh"